image: jcr-large-files.sensorsdata.cn/docker-impala/com.sensorsdata.dragon/bite_kudu:1.14.2.1

variables:
  THIRDPARTY_DIR: "/opt/code/kudu/thirdparty"
  CODE_ROOT: "/builds/sensors-analytics/kudu"
  GRADLE_USER_HOME: "${CODE_ROOT}/java/.gradle"
  KUDU_USE_LARGE_KEYS_IN_TESTS: 0
  NO_REBUILD_THIRDPARTY: 1

cache:
  key: kudu_114_3_java_cache
  when: 'on_success'
  paths:
    - ${GRADLE_USER_HOME}/caches
    - ${GRADLE_USER_HOME}/wrapper
  policy: pull-push

stages:
  - style_check
  - test

job ilint:
  stage: style_check
  script:
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make ilint -j32
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job tidy:
  stage: style_check
  script:
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make tidy -j32
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job iwyu:
  stage: style_check
  script:
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make iwyu -j32
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job asan:
  stage: test
  script:
    - export KUDU_ALLOW_SLOW_TESTS=0
    - mkdir -p build/asan
    - cd build/asan
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DKUDU_USE_ASAN=1 ../..
    - make -j32
    - cd ../..
    - bash check_test.sh
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job debug:
  stage: test
  script:
    - export KUDU_ALLOW_SLOW_TESTS=0
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make -j32
    - cd ../..
    - bash check_test.sh
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job tsan:
  stage: test
  script:
    - export KUDU_ALLOW_SLOW_TESTS=0
    - mkdir -p build/tsan
    - cd build/tsan
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DKUDU_USE_TSAN=1 ../..
    - make -j32
    - cd ../..
    - bash -x check_test.sh
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

