image: jcr-large-files.sensorsdata.cn/docker-inf/kudu/bite_ksyncer_el7:1.14.0.4

variables:
  THIRDPARTY_DIR: "/opt/code/kudu/thirdparty"
  CODE_ROOT: "/builds/sensors-analytics/kudu"
  GRADLE_USER_HOME: "${CODE_ROOT}/java/.gradle"
  KUDU_USE_LARGE_KEYS_IN_TESTS: 0
  NO_REBUILD_THIRDPARTY: 1

stages:
  - full_parallel

job ilint:
  stage: full_parallel
  script:
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make ilint -j$(nproc)
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job tidy:
  stage: full_parallel
  script:
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make tidy -j$(nproc)
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job iwyu:
  stage: full_parallel
  script:
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make iwyu -j$(nproc)
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job asan:
  stage: full_parallel
  script:
    - export KUDU_ALLOW_SLOW_TESTS=0
    - mkdir -p build/asan
    - cd build/asan
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DKUDU_USE_ASAN=1 ../..
    - make -j$(nproc)
    - cd ../..
    - bash check_test.sh
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job debug:
  stage: full_parallel
  script:
    - export KUDU_ALLOW_SLOW_TESTS=0
    - mkdir -p build/debug
    - cd build/debug
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DCMAKE_BUILD_TYPE=debug ../..
    - make -j$(nproc)
    - cd ../..
    - bash check_test.sh
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

job tsan:
  stage: full_parallel
  script:
    - export KUDU_ALLOW_SLOW_TESTS=0
    - mkdir -p build/tsan
    - cd build/tsan
    - CC=${THIRDPARTY_DIR}/clang-toolchain/bin/clang CXX=${THIRDPARTY_DIR}/clang-toolchain/bin/clang++ ${THIRDPARTY_DIR}/installed/common/bin/cmake -DKUDU_USE_TSAN=1 ../..
    - make -j$(nproc)
    - cd ../..
    - bash -x check_test.sh
  tags:
    - skv-kudu-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "CMakeLists.txt"
        - "build-support/**/*"
        - "check_test.sh"
        - "cmake_modules/*"
        - "src/kudu/**/*"
        - "thirdparty/**/*"
        - ".gitlab-ci.yml"
      when: always
    - when: never

