build_modules:
  bootstrap:
    - type: dragon

  construction_blueprint:
    - type: dragon
      add_cmds:
        - [ "COPY", "../soku-construction-blueprint/", "./" ]

  kudu_shim:
    - type: dragon
      add_cmds:
        - ["COPY", "../shim/*", "./"]

  upgrader:
    - type: dragon
      add_cmds:
        - [ "COPY", "../soku-upgrader/", "./" ]

  admintools:
    - type: dragon
      add_cmds:
        - ["COPY", "../admintools/*", "./"]

  scheduler_job:
    - type: dragon
      add_cmds:
        - ["COPY", "../scheduler_job/*", "./"]
