# 参考文档: https://doc.sensorsdata.cn/pages/viewpage.action?pageId=103014492
build_modules:
  # 模块名是 kudu
  kudu:
    # 为了支持多变体，添加 variants 字段
    variants:
      # os_distro: The common name of the operating system distribution
      - os_distro: el6
      - os_distro: el7
    types:
      # 制品类型是 dragon，既 "标准模块 tar 包"
      - type: dragon
        # 添加自定义 build 命令
        add_cmds:
          - ["RUN", "sh ./prebuild-tools/get_prebuid_package.sh"]
          - ["COPY", "./binary/installed/*", "./"]
      - type: docker
        args:
          DOCKERFILE_PATH: build-tools/dockerfiles/kudu
        add_cmds:
          - ["RUN", "sh ./prebuild-tools/collect_artifacts.sh"]

  cdh_parcel:
    variants:
      - os_distro: el6
      - os_distro: el7
    types:
      - type: dragon
        add_cmds:
          - ["RUN", "sh ./parcel-tools/soku_parcel.sh --version $MOD_FULL_VER"]
          - ["COPY", "./binary/cdh_parcel/*", "./"]

  collector:
    variants:
      - os_distro: el6
      - os_distro: el7
    types:
      - type: dragon
        add_cmds:
          # 这里需要执行get_prebuid_package的原因是整个编译不会按build.yml的顺序来保证执行顺序
          - ["RUN", "sh ./prebuild-tools/get_prebuid_package.sh"]
          - ["COPY", "./binary/installed/*", "./"]
          - ["COPY", "soku-construction-blueprint/step/start_kudu_collector.sh", "./"]

  soku_tool:
    variants:
      - os_distro: el6
      - os_distro: el7
    types:
      - type: dragon
        add_cmds:
          # 这里需要执行get_prebuid_package的原因是整个编译不会按build.yml的顺序来保证执行顺序
          - ["RUN", "sh ./prebuild-tools/get_prebuid_package.sh"]
          - ["COPY", "./binary/installed/sbin/kudu", "./"]
          - ["COPY", "./binary/installed/sbin/kudu", "./sp_kudu"]

  kudu_guidance:
    variants:
      - os_distro: el6
      - os_distro: el7
    types:
      - type: dragon
        add_cmds:
          # 这里需要执行get_prebuid_package的原因是整个编译不会按build.yml的顺序来保证执行顺序
          - ["RUN", "sh ./prebuild-tools/get_prebuid_package.sh"]
          - ["COPY", "./guidance/*", "./" ]
          - ["COPY", "./binary/installed/sbin/kudu", "./kudu/command"]
