package_modules:
  kudu:
    source: local
    variants:
      - os_distro: el6
      - os_distro: el7
    version: "1.14.1"
    pub:
      - type: dragon

  cdh_parcel:
    source: local
    variants:
      - os_distro: el6
      - os_distro: el7
    version: "1.14.1"
    pub:
      - type: dragon

  collector:
    source: local
    variants:
      - os_distro: el6
      - os_distro: el7
    version: "1.14.1"
    pub:
      - type: dragon

  soku_tool:
    source: local
    variants:
      - os_distro: el6
      - os_distro: el7
    version: "1.14.1"
    pub:
      - type: dragon
